// Generated by https://quicktype.io

export interface ViewPoint {
  ScenicSpotID: string;
  ScenicSpotName: string;
  DescriptionDetail: string;
  Description: string;
  Phone: string;
  Address: string;
  ZipCode: string;
  TravelInfo?: string;
  OpenTime: string;
  Picture: Picture;
  Position: Position;
  ParkingPosition: ParkingPosition;
  TicketInfo?: string;
  Remarks?: string;
  SrcUpdateTime: Date;
  UpdateTime: Date;
  Class1?: string;
  Level?: string;
  MapUrl?: string;
  Class2?: string;
  Class3?: string;
}

export interface ParkingPosition {
}

export interface Picture {
  PictureUrl1?: string;
  PictureDescription1?: string;
  PictureUrl2?: string;
  PictureDescription2?: string;
}

export interface Position {
  PositionLon: number;
  PositionLat: number;
  GeoHash: string;
}
